# version: '3.8'

networks:
  external_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
  internal_private:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
    # internal: true # This is to completely shut off native internet access
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  gateway_server:
    build: .  # from Dockerfile
    # image: ubuntu:24.04
    container_name: gateway_server
    # privileged: true
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "iptables -t nat -A POSTROUTING -s 172.18.0.0/16 ! -d 172.18.0.0/16 -j MASQUERADE && sleep infinity"
    # command: sleep infinity  # in Dockerfile
    networks:
      external_bridge:
      internal_private:
        ipv4_address: 172.18.0.10

  internal_server:
    build: . # from Dockerfile
    # image: ubuntu:24.04
    container_name: internal_server
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && ip route add default via 172.18.0.10 && sleep infinity"
    # command: sleep infinity # in Dockerfile
    networks:
      internal_private:
        ipv4_address: 172.18.0.2
    #depends_on:
     # - gateway_server

